set noautoindent
"colorscheme delek
"colorscheme desert
"colorscheme blue
colorscheme elflord
"colorscheme evening
"colorscheme koehler
"colorscheme morning
"colorscheme murphy
"colorscheme pablo
"colorscheme peachpuff
"colorscheme ron
"colorscheme shine
"colorscheme slate
"colorscheme torte
"colorscheme zellner
set tabstop=4
set shiftwidth=4
set expandtab

